config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
  root 'admin/sites#dashboard'
  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    registrations:  'admins/registrations',
    passwords:      'admins/passwords',
    unlocks:        'admins/unlocks',
    confirmations:  'admins/confirmations'
  }

  namespace :admin do
    get "/dashboard" => "sites#dashboard"
    get "/bulk_import" => "employees#bulk_import"
    get "/manager" => "employees#manager"
    get "/subordinate" => "employees#subordinate"
    post "/assign_manager" => "employees#assign_manager"
    post "/assign_subordinate" => "employees#assign_subordinate"
    post "/save_grade" => "employees#save_grade"
    resources :employee_relatives
    resources :educational_credentials
    resources :departments
    resources :employee_steps
    resources :email_notifications
    resources :bank_details
    resources :employees do
      collection { post :import }
    end  
  end 
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department, optional: true
  has_many :educational_credentials
  has_many :employee_relatives
  has_one :bank_detail
  belongs_to :employee_grade, optional: true
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee", optional: true
  has_many :email_employee_notifications
  has_many :email_notifications, through: :email_employee_notifications
  # validates :first_name, :middle_name, :last_name, :email, :date_of_birth, :personal_contact, :emergency_contact, :address, :city, :state, :country, :zipcode, :job_title, :job_description, :gender, :marital_status, :blood_group, :religion, :employee_code, :is_active, presence: true

  def name
    "#{self.first_name} #{self.middle_name} #{self.last_name}".strip
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Employee.create! row.to_hash
    end
  end    

  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < AdminController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  def index
    @employees = Employee.all
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def new
    @employee = Employee.new
  end

  def import
    Employee.import(params[:file])
    redirect_to admin_employees_path(@employee), notice: "Employee imported."
  end

  def bulk_import; end

  def edit; end

  def manager
   @employee = Employee.find(params[:employee_id]) 
  end

  def assign_manager
    @manager = Employee.find(params[:manager][:manager_id])
    @subordinate = Employee.find(params[:manager][:employee_id])
    @subordinate.manager = @manager
    @subordinate.save
    EmployeeMailer.subordinate_email(@subordinate).deliver_now && EmployeeMailer.manager_email(@manager).deliver_now
    redirect_to admin_employees_path(@employee)
  end

  def subordinate
    @employee = Employee.find(params[:employee_id]) 
  end

  def assign_subordinate
    @subordinate = Employee.find(params[:subordinate][:employee_id])
    @manager = Employee.find(params[:subordinate][:manager_id])
    @manager.subordinates <<  @subordinate
    EmployeeMailer.manager_email(@manager, @subordinate).deliver_now
    EmployeeMailer.subordinate_email(@subordinate).deliver_now
    redirect_to admin_employees_path(@manager)
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      session[:employee_id] = @employee.id
      redirect_to admin_employee_steps_path, notice: 'Profile was successfully created.'
    else
      render :new 
    end
  end

  def update
    if @employee.update(employee_params)
      session[:employee_id] = @employee.id
      redirect_to admin_employee_steps_path, notice: 'Employee was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to admin_employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def save_grade
    @employee = Employee.find(params[:employee_grade][:employee_id])
    respond_to do |format|
      if @employee.update(employee_grade_id: params[:employee_grade][:employee_grade_id])
        format.js
        format.html { redirect_to admin_employees_path, notice: 'Employe grade assigned.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :save_grade }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end  
  end 

  private
    

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit!
    end
end

app/views/admin/employees/_assign_grade.html.erb
<!-- Modal -->
<div class="modal fade" id="gradeModal" tabindex="-1" role="dialog" aria-labelledby="gradeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="gradeModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for :employee_grade, url: :admin_save_grade, remote: true do |form| %>
        <div class="modal-body">
          <div class="form-group">
            <%= form.label :select_employee_grade %>
            <%= form.hidden_field :employee_id, value: @employee.id %>  
            <%= form.select :employee_grade_id, options_for_select(EmployeeGrade.all.map {|employee_grade| [employee_grade.name, employee_grade.id]}, selected: form.object.try(:employee_grade)), { include_blank: "Select Employee grade" }, { class: "form-control form-control-line rounded-0", required: true } %>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit  class: "btn btn-primary" %>
        </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/admin/employees/_employee.html.erb
<table class="table table-bordered mt-4">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Profile</th>
      <th>Assigned Users</th>
      <th>Actions</th>          
    </tr>
  </thead>
  <% @department.employees.order(is_manager: :desc).each do |employee| %>
    <tbody>
        <tr>
        <td><%= image_tag "employee.jpg", class: "rounded-circle image" %></td>
        <td><%= employee.name %></td>
        <td>
          <% if employee.is_manager %>
           <span class="badge badge-success">Manger</span>
          <% else %>
           <span class="badge badge-danger">subordinate </span>
          <% end %>
        </td>  
        <% if employee.is_manager %>
          <td>
            <strong>Subordinates:</strong> 
            <% employee.subordinates.each do |sub_ordinates| %>    
              <li>
                <%= sub_ordinates.name %>                  
              </li>
            <% end %>
          </td>  
        <% else %>
          <td>
            <strong>Manager:</strong> 
            <% if employee.manager.present? %>
              <li>
                <%= employee.manager.name  %>
              </li> 
            <% end %>
          </td> 
        <% end %>  
        <td><%= link_to 'View Profile', admin_employee_path(employee), class: "btn btn-info waves-effect waves-light btn-sm" %></td>
        </tr>
    </tbody>
  <% end %>  

</table>


<style type="text/css">
  .image{
    width: 50px;
  }
</style>

app/views/admin/employees/_form.html.erb
<%= form_for [:admin, @employee], html: {id: 'employee_form'} do |form| %>

  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :profile_photo %>
      <%= form.file_field :profile_photo %>
    </div>  
    <div class="form-group col-md-6 mt-0">
      <%= form.label :is_active %>
      <%= form.check_box :is_active %>
    </div> 
  </div>
  <div class="row">  
    <div class="form-group col-md-6">
      <%= form.label :is_manager %>
      <%= form.check_box :is_manager %>
    </div>   
  </div>

  <div class="actions">
    <%= form.submit "Continue", class: "btn btn-primary rounded-0" %>
  </div>
<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBFBYM37YGMTdgkEp9fipPljSjprTDZL8Y&libraries&libraries=places&callback=initAutocomplete"
    async defer></script>
<script type="text/javascript">
  var placeSearch, autocomplete;
  var componentForm = {
  locality: 'long_name',
  administrative_area_level_1: 'long_name',
  country: 'long_name',
  postal_code: 'short_name'
};
function initAutocomplete() {
  autocomplete = new google.maps.places.Autocomplete(
      /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
      {types: ['geocode']});
  autocomplete.addListener('place_changed', fillInAddress);
}
function fillInAddress() {
  var place = autocomplete.getPlace();
  $("#latitude").val(place.geometry.location.lat());
  $("#longitude").val(place.geometry.location.lng());
  for (var component in componentForm) {
    document.getElementById(component).value = '';
    document.getElementById(component).disabled = false;
  }
  for (var i = 0; i < place.address_components.length; i++) {
    var addressType = place.address_components[i].types[0];
    if (componentForm[addressType]) {
      var val = place.address_components[i][componentForm[addressType]];
      document.getElementById(addressType).value = val;
    }
  }
}
function geolocate() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var geolocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };
      var circle = new google.maps.Circle({
        center: geolocation,
        radius: position.coords.accuracy
      });
      autocomplete.setBounds(circle.getBounds());
    });
  }
}
</script>

app/views/admin/employees/_profile.html.erb
<p>
  <%= image_tag 'male.jpg', class: "image"%>
</p>
<% if @employee.employee_grade.present? %>
  <p>Grade:-<%= @employee.employee_grade.name %></p>
<% end %>  
<p>
  <span class="badge badge-<%= @employee.is_active ? 'success' : 'danger' %>"><%= @employee.is_active ? 'Active' : 'Inactive' %></span>
</p>
<%= link_to 'Edit', edit_admin_employee_path(@employee), class: "btn btn-warning btn-sm" %> 
<%= link_to 'Back', admin_employees_path, class: "btn btn-info btn-sm" %><br>
<% if @employee.is_active %>
  <% if @employee.is_manager %>
    <%= link_to 'Assign subordinate', admin_subordinate_path(employee_id: @employee), class: "btn btn-primary btn-sm mt-2" %>
  <% else %>
    <%= link_to 'Assign manager', admin_manager_path(employee_id: @employee), class: "btn btn-primary btn-sm mt-2" %> 
  <% end %>      
<% end %>        

<button type="button" class="btn btn-success btn-sm mt-2" data-toggle="modal" data-target="#gradeModal">
  Assign grade
</button>
<%=  render 'admin/employees/assign_grade' %>

app/views/admin/employees/bulk_import.html.erb
<div class="container">
  <div class="card mt-4">
    <div class="card-header">
      <h2 class="card-heading">Import Employees</h2>      
    </div>    
    <div class="card-body">
      <%= form_tag import_admin_employees_path, multipart: true do %>
       <%= file_field_tag :file %>
       <%= submit_tag "Import", class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>  
  </div>  
</div>

app/views/admin/employees/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-heading">Editing Employee</h3>          
        </div>
        <div class="card-body">
          <%= render 'form', employee: @employee %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/employees/index.html.erb
<div class="container">
  <div class="card mt-3">
    <div class="card-body">
      <%= render 'admin/employees/index/filter' %>      
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card mt-5 mb-5">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h1>Listing Employees</h1>        
            </div>
            <div class="col-md-6">
              <div class="float-right">
                <%= link_to 'Bulk Import', admin_bulk_import_path, class: "btn btn-primary rounded-0" %> 
                <%= link_to 'New Employee', new_admin_employee_path, class: "btn btn-primary rounded-0" %>
              </div>              
            </div>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>City</th>
              <th>Country</th>
              <th>Job title</th>
              <th>DOJ</th>
              <th>Code</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td><%= employee.name %></td>
                <td><%= employee.city %></td>
                <td><%= employee.country %></td>
                <td><%= employee.job_title %></td>
                <td><%= employee.date_of_joining %></td>
                <td><%= employee.employee_code %></td>
                <td>
                  <% if employee.is_active %>
                    <span class="badge badge-success">Active</span>
                  <% else %>
                    <span class="badge badge-danger">In Active</span>
                  <% end %>
                </td>
                <td>
                  <div class="dropdown">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Actions</button>
                    <div class="dropdown-menu">                                   
                      <%= link_to 'Show', admin_employee_path(employee), class: "dropdown-item" %>
                      <%= link_to 'Edit', edit_admin_employee_path(employee), class: "dropdown-item" %>
                      <%= link_to  'Destroy', admin_employee_path(employee), method: :delete, data: {   confirm: 'Are you sure?' }, class: "dropdown-item"  %>
                    </div>  
                  </div>    
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>        
        <%= paginate @employees, theme: 'twitter-bootstrap-4',
                   pagination_class: "pagination-sm",
                   nav_class: "d-inline-b" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/employees/manager.html.erb
<%= form_for :manager, url: :admin_assign_manager, method: :post  do |form| %>
  <%= form.hidden_field :employee_id, value: @employee.id %>
  <div class="form-group">
    <%= form.label :select_manager %>
    <%= form.select :manager_id, options_for_select(Employee.where(is_manager: true).map {|employee| [employee.name, employee.id]}, selected: form.object.try(:employee)), { include_blank: "Select Manager" }, { class: "form-control form-control-line rounded-0", required: true } %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<%end%>  

app/views/admin/employees/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-heading">New Employee</h3>          
        </div>
        <div class="card-body">
          <%= render 'form', employee: @employee %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/employees/save_grade.js.erb
$('#gradeModal').modal('hide');
$("#gradeDiv").html("<%= escape_javascript render(partial: 'profile')%>");
$('.modal-backdrop').remove();

app/views/admin/employees/show.html.erb
<div class="container">
  <%= render 'partials/flash' %>
  <div class="row">
    <div class="col-4 offset-4 text-center">
      <div class="card rounded-0 mb-5">
        <div class="card-body" id="gradeDiv">
          <%= render 'admin/employees/profile' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mx-md-auto">
      <div class="card rounded-0">
        <div class="card-header">
          <h5 class="">Basic Profile</h5>
        </div>
        <div class="card-body">
          <p>
            <strong>Name:</strong>
            <%= @employee.name.titleize %>
          </p>

          <p>
            <strong>Email:</strong>
            <%= @employee.email %>
          </p>

          <p>
            <strong>Date of birth:</strong>
            <%= @employee.date_of_birth %>
          </p>

          <p>
            <strong>Personal contact:</strong>
            <%= @employee.personal_contact %>
          </p>

          <p>
            <strong>Emergency contact:</strong>
            <%= @employee.emergency_contact %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6 mx-md-auto">
      <div class="card mb-5">
        <div class="card-header">
          <h5>Address</h5>
        </div>       
        <div class="card-body">
          <p>
            <strong>Address:</strong>
            <%= @employee.address %>
          </p>

          <p>
            <strong>City:</strong>
            <%= @employee.city %>
          </p>

          <p>
            <strong>State:</strong>
            <%= @employee.state %>
          </p>

          <p>
            <strong>Country:</strong>
            <%= @employee.country %>
          </p>

          <p>
            <strong>Zipcode:</strong>
            <%= @employee.zipcode %>
          </p>
        </div> 
      </div>
    </div>
  </div>  
  <div class="row">
    <div class="col-md-6 mx-md-auto">
      <div class="card">
        <div class="card-header">
          <h5>About Job</h5>
        </div>
        <div class="card-body">
          <p>
            <strong>Job title:</strong>
            <%= @employee.job_title %>
          </p>

          <p>
            <strong>Job description:</strong>
            <%= @employee.job_description %>
          </p>

          <p>
            <strong>Date of joining:</strong>
            <%= @employee.date_of_joining %>
          </p>

          <p>
            <strong>Employee code:</strong>
            <%= @employee.employee_code %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-6 mx-md-auto">
      <div class="card">
        <div class="card-header">
          <h5>Info</h5>
        </div>
        <div class="card-body">
          <p>
            <strong>Gender:</strong>
            <%= @employee.gender %>
          </p>

          <p>
            <strong>Marital status:</strong>
            <%= @employee.marital_status %>
          </p>

          <p>
            <strong>Blood group:</strong>
            <%= @employee.blood_group %>
          </p>

          <p>
            <strong>Religion:</strong>
            <%= @employee.religion %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% if @employee.is_manager %>
    <% if @employee.subordinates.present? %>
      <div class="row">
        <div class="col-md-6">   
          <div class="card mt-4">                 
            <div class="card-header">
              <h5 class="card-heading">Subordinates</h5>
            </div>
            <div class="card-body">
              <ul>
                <% @employee.subordinates.each do |sub_ordinates| %>    
                  <li>
                    <%= sub_ordinates.name %>                  
                  </li>
                <% end %>              
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>          
  <% else %>
    <% if @employee.manager.present? %>
      <div class="row">
        <div class="col-md-6">
          <div class="card mt-4"> 
            <div class="card-header">
              <h5 class="card-heading">Manger</h5>
            </div>
            <div class="card-body">
              <ul>
                <li>
                  <%= @employee.manager.name %>                            
                </li>
              </ul>
           </div>
         </div>
        </div>
      </div>
    <%end%>
  <% end %>
  <div class="card mt-4">
    <div class="card-header">
      <h5>Eductaional Credentials</h5>
    </div>
  </div>        
  <div class="row"> 
    <div class="col-md-12">
      <div class="row">
        <%= render @employee.educational_credentials %>        
      </div>
    </div>
  </div>
 
  <div class="card mt-4">
    <div class="card-header">
      <h5>Employee Relative</h5>
    </div>
  </div>
  <div class="row"> 
    <div class="col-md-12">
      <div class="row">
        <%= render @employee.employee_relatives %>        
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .image{
    width: 100px;
  }
</style>

app/views/admin/employees/subordinate.html.erb
<%= form_for :subordinate, url: :admin_assign_subordinate, method: :post  do |form| %>
  <%= form.hidden_field :manager_id, value: @employee.id %>
  <div class="form-group">
    <%= form.label :select_subordinate %>
    <%= form.select :employee_id, options_for_select(Employee.where(is_manager: false).map {|employee| [employee.name, employee.id]}, selected: form.object.try(:employee)), { include_blank: "Select Subordinate" }, { class: "form-control form-control-line rounded-0", required: true } %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<%end%>  