config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
  root 'admin/sites#dashboard'
  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    registrations:  'admins/registrations',
    passwords:      'admins/passwords',
    unlocks:        'admins/unlocks',
    confirmations:  'admins/confirmations'
  }

  namespace :admin do
    get "/dashboard" => "sites#dashboard"
    get "/bulk_import" => "employees#bulk_import"
    get "/manager" => "employees#manager"
    get "/subordinate" => "employees#subordinate"
    post "/assign_manager" => "employees#assign_manager"
    post "/assign_subordinate" => "employees#assign_subordinate"
    post "/save_grade" => "employees#save_grade"
    resources :employee_relatives
    resources :educational_credentials
    resources :departments
    resources :employee_steps
    resources :email_notifications
    resources :bank_details
    resources :employees do
      collection { post :import }
    end  
  end 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_detail.rb
class BankDetail < ApplicationRecord
  include Employeeable
  
  BANK = ['ALLAHABAD BANK', 'ANDHRA BANK','BANK OF BARODA', 'BANK OF INDIA','BANK OF MAHARASHTRA','CANARA BANK','CENTRAL BANK OF INDIA','CORPORATION BANK','INDIAN BANK','INDIAN OVERSEAS BANK','ORIENTAL BANK OF COMMERCE','PUNJAB AND SIND BANK','PUNJAB NATIONAL BANK','STATE BANK OF INDIA','SYNDICATE BANK','UCO BANK','UNION BANK OF INDIA','UNITED BANK OF INDIA', 'HDFC BANK','ICICI BANK','AXIS BANK','KOTAK MAHINDRA BANK','YES BANK','FEDRAL BANK','INDUSLAND BANK','RBL BANK','KARUR VYSYA BANK','BANDHAN BANK']
  
  validates :employee_id, uniqueness: { scope: :employee_id, message: 'has already bank account.' }
  validates :bank_name, :account_number, :branch, :ifsc_code, presence: true

end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
  validates :name, presence: true, uniqueness: true 
end

app/models/educational_credential.rb
class EducationalCredential < ApplicationRecord  
  include Employeeable
  validates :course, :board_or_university, :city, :marks, presence: true 
end

app/models/email_employee_notification.rb
class EmailEmployeeNotification < ApplicationRecord
  belongs_to :employee
  belongs_to :email_notification
  mount_uploader :attachment, AttachmentUploader
end

app/models/email_notification.rb
class EmailNotification < ApplicationRecord
  has_many :email_employee_notifications, dependent: :destroy
  has_many :employees, through: :email_employee_notifications
  mount_uploader :attachment, AttachmentUploader
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department, optional: true
  has_many :educational_credentials
  has_many :employee_relatives
  has_one :bank_detail
  belongs_to :employee_grade, optional: true
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee", optional: true
  has_many :email_employee_notifications
  has_many :email_notifications, through: :email_employee_notifications
  # validates :first_name, :middle_name, :last_name, :email, :date_of_birth, :personal_contact, :emergency_contact, :address, :city, :state, :country, :zipcode, :job_title, :job_description, :gender, :marital_status, :blood_group, :religion, :employee_code, :is_active, presence: true

  def name
    "#{self.first_name} #{self.middle_name} #{self.last_name}".strip
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Employee.create! row.to_hash
    end
  end    

  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end
end

app/models/employee_grade.rb
class EmployeeGrade < ApplicationRecord
  has_many :employees
  validates :name,  presence: true
end

app/models/employee_relative.rb
class EmployeeRelative < ApplicationRecord
  include Employeeable
  validates :name, :contact, :address, :relation, presence: true 
end

app/models/leave.rb
class Leave < ApplicationRecord
  include Employeeable
  validate :check_total_assigned_leaves
 
  def check_total_assigned_leaves
    if employee.employee_grade.present? 
      grade_name = employee.employee_grade.name
      if grade_name == 'A'
        if total_assigned_leaves.to_i > 16
          errors.add('Leaves',  "can not be greater than 16 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 16
          errors.add('Leaves',  "can not be less than 16 for grade #{grade_name} employee")
        end
      elsif grade_name == 'B'
        if total_assigned_leaves.to_i > 12
          errors.add('Leaves', "can not be greater than 12 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 12
          errors.add('Leaves', "can not be less than `12 for grade #{grade_name} employee")    
        end   
      elsif grade_name == 'C'
        if total_assigned_leaves.to_i > 10
          errors.add('Leaves', "can not be greater than 10 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 10
          errors.add('Leaves', "can not be less than 10 for grade #{grade_name} employee")    
        end
      elsif grade_name == 'D'
        if total_assigned_leaves.to_i > 8
          errors.add('Leaves', "can not be greater than 8 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 8
          errors.add('Leaves', "can not be less than 8 for grade #{grade_name} employee")    
        end
      end        
    end
  end  
end

app/controllers/admin/educational_credentials_controller.rb
class Admin::EducationalCredentialsController < AdminController
  before_action :set_educational_credential, only: [:edit, :show, :destroy, :update]
  
  def index
    @educational_credentials = EducationalCredential.all
  end

  def show;  end

  def edit;  end

  def new
    @educational_credential = EducationalCredential.new
  end

  def create
    @educational_credential = EducationalCredential.new(educational_credential_params)
    if @educational_credential.save
     redirect_to admin_educational_credential_path(@educational_credential), notice: "educational_credential has been created successfully."
    else
      render 'new'
    end      
  end 

  def update
    if @educational_credential.update(educational_credential_params)
      redirect_to admin_educational_credential_path(@educational_credential), notice: "educational_credential has been updated successfully."
    else
      render 'edit'
    end    
  end
 
  def destroy
    @educational_credential.destroy
    redirect_to admin_educational_credentials_path, notice: "Educational credential has been deleted successfully."
  end

  private

    def educational_credential_params
      params.require(:educational_credential).permit!
    end

    def set_educational_credential
      @educational_credential = EducationalCredential.find(params[:id])
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  helper_method :current_employee
  skip_before_action :verify_authenticity_token
  before_action :authenticate_admin!
  private

  def current_employee
    @current_employee ||= Employee.find_by_id(session[:employee_id]) if session[:employee_id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/educational_credential_helper.rb
module EducationalCredentialHelper
end

app/helpers/educational_credentials_helper.rb
module EducationalCredentialsHelper
end

app/helpers/email_notifications_helper.rb
module EmailNotificationsHelper
end

app/helpers/employee_relative_helper.rb
module EmployeeRelativeHelper
end

app/helpers/employee_relatives_helper.rb
module EmployeeRelativesHelper
end

app/helpers/employee_steps_helper.rb
module EmployeeStepsHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/admin/educational_credentials/_educational_credential.html.erb
<div class="col-12 col-md-3">
  <div class="card mt-4">
    <div class="card-body">
      <div class="text-center">
        <h5 class="font-weight-bold mt-3"><%= educational_credential.course %></h5>
        <h6 class="font-weight-bold"> <%= educational_credential.board_or_university %></h6>
        <h5 class="text-dark"><%= educational_credential.city %></h5> 
        <h5 class="text-dark"><%= educational_credential.marks %></h5>
      </div>
    </div>
  </div>      
</div>

app/views/admin/educational_credentials/_form.html.erb
<%= form_for [:admin, @educational_credential], html: {id: 'educational_credential_form'} do |form| %>
 
  <% if @educational_credential.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@educational_credential.errors.count, "error") %> prohibited
        this educational_credential from being saved:
      </h2>
      <ul>
        <% @educational_credential.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :course %>
      <%= form.text_field :course, class: "form-control rounded-0" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :board_or_university %>
      <%= form.text_field :board_or_university, class: "form-control rounded-0" %>
    </div>
  </div> 
 
  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :city %>
      <%= form.text_field :city, class: "form-control rounded-0" %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :marks %>
      <%= form.text_field :marks, class: "form-control rounded-0" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :select_employee %>
    <%= form.select :employee_id, options_for_select(Employee.all.map {|employee| [employee.name, employee.id]}, selected: form.object.try(:employee)), { include_blank: "Select Employee" }, { class: "form-control form-control-line rounded-0", required: true } %>
  </div>
 
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Back', admin_educational_credentials_path, class: "btn btn-outline-primary" %>
  </div>
 
<% end %>

app/views/admin/educational_credentials/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card rounded-0">
        <div class="card-header">
          <h5 class="card-heading">Edit Education Credentials</h5>
        </div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/educational_credentials/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h1>Listing Educational Credentials</h1>
            </div>
            <div class="col-md-6">
              <%= link_to 'New Educational Credentials', new_admin_educational_credential_path, class: "btn btn-primary rounded-0 float-right" %>
            </div>
          </div>
        </div>
      </div>
      <table class="table table-bordered">
        <tr>
          <th>Course</th>
          <th>Board or University</th>
          <th>City</th>
          <th>Marks</th>
          <th colspan="3">Actions</th>
        </tr>
       
        <% @educational_credentials.each do |educational_credential| %>
          <tr>
            <td><%= educational_credential.course %></td>
            <td><%= educational_credential.board_or_university %></td>
            <td><%= educational_credential.city %></td>
            <td><%= educational_credential.marks %></td>
            <td>
              <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Actions</button>
                <div class="dropdown-menu">
                  <%= link_to 'Show', admin_educational_credential_path(educational_credential), class: "dropdown-item" %>
                  <%= link_to 'Edit', edit_admin_educational_credential_path(educational_credential), class: "dropdown-item" %>
                  <%= link_to 'Destroy', admin_educational_credential_path(educational_credential), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
                </div>  
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/educational_credentials/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card rounded-0">
        <div class="card-header">
          <h5 class="card-heading">New Education Credentials</h5>
        </div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/educational_credentials/show.html.erb
<div class="row">
  <div class="col-12">
    <%= render 'partials/flash' %>
    <div class="card rounded-0">
      <div class="card-body">
        <p>
          <strong>Course:</strong>
          <%= @educational_credential.course %>
        </p>
         
        <p>
          <strong>Board or University:</strong>
          <%= @educational_credential.board_or_university %>
        </p>
         
        <p>
          <strong>Name:</strong>
          <%= @educational_credential.city %>
        </p>
         
        <p>
          <strong>Established from:</strong>
          <%= @educational_credential.marks %>
        </p>
         
        <%= link_to 'Edit', edit_admin_educational_credential_path(@educational_credential), class: "btn btn-warning btn-sm" %>  
        <%= link_to 'Back', admin_educational_credentials_path, class: "btn btn-info btn-sm" %>        
      </div>
    </div>
  </div>
</div>