config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  
  root 'admin/sites#dashboard'
  devise_for :admins, controllers: {
    sessions:       'admins/sessions',
    registrations:  'admins/registrations',
    passwords:      'admins/passwords',
    unlocks:        'admins/unlocks',
    confirmations:  'admins/confirmations'
  }

  namespace :admin do
    get "/dashboard" => "sites#dashboard"
    get "/bulk_import" => "employees#bulk_import"
    get "/manager" => "employees#manager"
    get "/subordinate" => "employees#subordinate"
    post "/assign_manager" => "employees#assign_manager"
    post "/assign_subordinate" => "employees#assign_subordinate"
    post "/save_grade" => "employees#save_grade"
    resources :employee_relatives
    resources :educational_credentials
    resources :departments
    resources :employee_steps
    resources :email_notifications
    resources :bank_details
    resources :employees do
      collection { post :import }
    end  
  end 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_detail.rb
class BankDetail < ApplicationRecord
  include Employeeable
  
  BANK = ['ALLAHABAD BANK', 'ANDHRA BANK','BANK OF BARODA', 'BANK OF INDIA','BANK OF MAHARASHTRA','CANARA BANK','CENTRAL BANK OF INDIA','CORPORATION BANK','INDIAN BANK','INDIAN OVERSEAS BANK','ORIENTAL BANK OF COMMERCE','PUNJAB AND SIND BANK','PUNJAB NATIONAL BANK','STATE BANK OF INDIA','SYNDICATE BANK','UCO BANK','UNION BANK OF INDIA','UNITED BANK OF INDIA', 'HDFC BANK','ICICI BANK','AXIS BANK','KOTAK MAHINDRA BANK','YES BANK','FEDRAL BANK','INDUSLAND BANK','RBL BANK','KARUR VYSYA BANK','BANDHAN BANK']
  
  validates :employee_id, uniqueness: { scope: :employee_id, message: 'has already bank account.' }
  validates :bank_name, :account_number, :branch, :ifsc_code, presence: true

end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
  validates :name, presence: true, uniqueness: true 
end

app/models/educational_credential.rb
class EducationalCredential < ApplicationRecord  
  include Employeeable
  validates :course, :board_or_university, :city, :marks, presence: true 
end

app/models/email_notification.rb
class EmailNotification < ApplicationRecord
  has_many :email_employee_notifications, dependent: :destroy
  has_many :employees, through: :email_employee_notifications
  mount_uploader :attachment, AttachmentUploader
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department, optional: true
  has_many :educational_credentials
  has_many :employee_relatives
  has_one :bank_detail
  belongs_to :employee_grade, optional: true
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
  belongs_to :manager, class_name: "Employee", optional: true
  has_many :email_employee_notifications
  has_many :email_notifications, through: :email_employee_notifications
  # validates :first_name, :middle_name, :last_name, :email, :date_of_birth, :personal_contact, :emergency_contact, :address, :city, :state, :country, :zipcode, :job_title, :job_description, :gender, :marital_status, :blood_group, :religion, :employee_code, :is_active, presence: true

  def name
    "#{self.first_name} #{self.middle_name} #{self.last_name}".strip
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Employee.create! row.to_hash
    end
  end    

  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end
end

app/models/employee_grade.rb
class EmployeeGrade < ApplicationRecord
  has_many :employees
  validates :name,  presence: true
end

app/models/employee_relative.rb
class EmployeeRelative < ApplicationRecord
  include Employeeable
  validates :name, :contact, :address, :relation, presence: true 
end

app/models/leave.rb
class Leave < ApplicationRecord
  include Employeeable
  validate :check_total_assigned_leaves
 
  def check_total_assigned_leaves
    if employee.employee_grade.present? 
      grade_name = employee.employee_grade.name
      if grade_name == 'A'
        if total_assigned_leaves.to_i > 16
          errors.add('Leaves',  "can not be greater than 16 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 16
          errors.add('Leaves',  "can not be less than 16 for grade #{grade_name} employee")
        end
      elsif grade_name == 'B'
        if total_assigned_leaves.to_i > 12
          errors.add('Leaves', "can not be greater than 12 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 12
          errors.add('Leaves', "can not be less than `12 for grade #{grade_name} employee")    
        end   
      elsif grade_name == 'C'
        if total_assigned_leaves.to_i > 10
          errors.add('Leaves', "can not be greater than 10 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 10
          errors.add('Leaves', "can not be less than 10 for grade #{grade_name} employee")    
        end
      elsif grade_name == 'D'
        if total_assigned_leaves.to_i > 8
          errors.add('Leaves', "can not be greater than 8 for grade #{grade_name} employee")
        elsif total_assigned_leaves.to_i < 8
          errors.add('Leaves', "can not be less than 8 for grade #{grade_name} employee")    
        end
      end        
    end
  end  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  helper_method :current_employee
  skip_before_action :verify_authenticity_token
  before_action :authenticate_admin!
  private

  def current_employee
    @current_employee ||= Employee.find_by_id(session[:employee_id]) if session[:employee_id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_details_helper.rb
module BankDetailsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/email_notifications_helper.rb
module EmailNotificationsHelper
end

app/helpers/employee_relative_helper.rb
module EmployeeRelativeHelper
end

app/helpers/employee_relatives_helper.rb
module EmployeeRelativesHelper
end

app/helpers/employee_steps_helper.rb
module EmployeeStepsHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already have an account?", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/partials/_admin_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; AppsImpact HRM 2019</span>
    </div>
  </div>
</footer>

app/views/partials/_admin_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>

  </ul>

</nav>

app/views/partials/_admin_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/admin/dashboard">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">AI HRM <sup>2</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="/admin/dashboard">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
    </a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Directories
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <%= link_to admin_departments_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-building"></i>
      <span>Departments</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to admin_employees_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-users"></i>
      <span>Employees</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to admin_educational_credentials_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-graduation-cap"></i>
      <span>Educational credentials</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to admin_employee_relatives_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-users"></i>
      <span>Employee Relative</span>
    <% end %>
  </li> 
  
  <li class="nav-item">
    <%= link_to admin_bank_details_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-bank"></i>
      <span>Bank Details</span>
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to admin_email_notifications_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-bank"></i>
      <span>Email Notification</span>
    <% end %>
  </li>

  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/views/partials/_flash.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %>
  </div>
<% end %> 

app/views/partials/_logout_popup.html.erb
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>